merged with the old-trunk lost changes

diff --git a/apps/diagnostic-report/tags/diagnostic-report-1.8/diagnostic-report b/apps/diagnostic-report/tags/diagnostic-report-1.8/diagnostic-report
--- a/apps/diagnostic-report/tags/diagnostic-report-1.8/diagnostic-report
+++ b/apps/diagnostic-report/tags/diagnostic-report-1.8/diagnostic-report
@@ -10,44 +10,21 @@
 # TODO:
 # - Añadir identificador al fichero generado
 
-if [ "$(whoami)" != "root" ]; then
-  zenity --error --title "Error" --text \
-"Esta aplicación requiere
-permisos de administración"
-
-  exit 1
-fi
-
-# Constants
-FICHERO_FINAL='informe_hardware'
-if [ -n "$SUDO_USER" ]; then
-        DIRECTORIO_FINAL=/home/$SUDO_USER/Escritorio
-	REAL_USER=$SUDO_USER
-else
-	DIRECTORIO_FINAL=$HOME/Escritorio
-	REAL_USER=$USER
-fi
-[ ! -d $DIRECTORIO_FINAL ] && mkdir -p $DIRECTORIO_FINAL
-FICHERO_SALIDA=$(mktemp)
-NOMBRE_PROGRAMA='Informe de hardware'
-
-> $FICHERO_SALIDA
-
 # Signal handlers
 
 # Functions
 show_file () {
-  fichero_a_mostrar=$1
-  echo '----------------------------------------------------------------------' >> $FICHERO_SALIDA
-  echo "FICHERO: $fichero_a_mostrar" >> $FICHERO_SALIDA
+  FILE_TO_SHOW=$1
+  echo '----------------------------------------------------------------------' >> $OUTPUT_FILE
+  echo $"FILE: $FILE_TO_SHOW" >> $OUTPUT_FILE
 
-  if [ -r $fichero_a_mostrar ]; then
-    cat $fichero_a_mostrar >> $FICHERO_SALIDA
+  if [ -r $FILE_TO_SHOW ]; then
+    cat $FILE_TO_SHOW >> $OUTPUT_FILE
     return
   fi
 
-  if [ ! -a $fichero_a_mostrar ]; then
-    echo "ERROR: El fichero no existe" >> $FICHERO_SALIDA
+  if [ ! -a $FILE_TO_SHOW ]; then
+    echo $"ERROR: File does not exist" >> $OUTPUT_FILE
     return
   fi
 
@@ -55,87 +32,137 @@ show_file () {
 
 
 show_binary_exit () {
-  binario_a_mostrar="$*"
-  echo '----------------------------------------------------------------------' >> $FICHERO_SALIDA
-  echo "COMANDO: $binario_a_mostrar" >> $FICHERO_SALIDA
+  BINARY_TO_SHOW="$*"
+  echo '----------------------------------------------------------------------' >> $OUTPUT_FILE
+  echo $"COMMAND: $BINARY_TO_SHOW" >> $OUTPUT_FILE
 
-  eval "$binario_a_mostrar" >> $FICHERO_SALIDA
+  eval "$BINARY_TO_SHOW" >> $OUTPUT_FILE
 }
 
+if [ "$(whoami)" != "root" ]; then
+  zenity --error --title "Error" --text \
+$"This application needs
+root privileges"
+  exit 1
+fi
+
+
+
+# Constants
+FINAL_LOGFILE='diagnostics_report'
+if [ -n "$SUDO_USER" ]; then
+	# include XDG dirs
+	test -f $SUDO_USER/.config/user-dirs.dirs && . /home/$SUDO_USER/.config/user-dirs.dirs
+        if [ -n $XDG_DESKTOP_DIR ]
+	then
+		DESTDIR=/home/$SUDO_USER/$XDG_DESKTOP_DIR
+	else
+		DESTDIR=/home/$SUDO_USER
+	fi
+	REAL_USER=$SUDO_USER
+else
+	# include XDG dirs
+	test -f $HOME/.config/user-dirs.dirs && . $HOME/.config/user-dirs.dirs
+	if [ -n $XDG_DESKTOP_DIR ]
+	then
+		DESTDIR=$HOME/$XDG_DESKTOP_DIR
+	else
+		DESTDIR=$HOME
+	fi
+	REAL_USER=$USER
+fi
+[ ! -d $DESTDIR ] && mkdir -p $DESTDIR
+OUTPUT_FILE=$(mktemp)
+APP_NAME=$"Informe de hardware"
+
+> $OUTPUT_FILE
 
 # main
 
-zenity --question --title "$NOMBRE_PROGRAMA" --text \
-"Este programa generará un informe con información de su ordenador que puede enviar voluntariamente al Servicio de Asistencia al Usuario para ayudar a la resolución de su problema. Este informe recoge únicamente información técnica y, en ningún caso, se recopila información personal como contraseñas, correo, etc. Una vez que se haya generado, se le dará la oportunidad de revisar su contenido.
+zenity --question --title "$APP_NAME" --text \
+$"This utility will make a report with some useful info from your computer which you can, voluntarily, send to the User Assistance Service to help you solving your problem.
+This report just contains technical info and, will never collect personal info like passwords, mails, etc.
+Once the report is done, you will be able to review its content.
 
-A continuación se procederá a generar el informe"
+Next, report generation will start."
 
 if [ $? == 1 ]; then
   exit
 fi
 
+# system wide related info
 show_file /etc/lsb-release
+show_binary_exit 'dmesg'
+
+# users related info
 show_binary_exit 'whoami'
 show_binary_exit 'date'
-
 show_binary_exit 'cut -d: -f 1,3,4 /etc/passwd'
 show_file '/etc/group'
 
+# X related info
 show_file '/etc/X11/xorg.conf'
 show_file '/var/log/Xorg.0.log'
 show_binary_exit 'ddcprobe'
+
+# disks related info
 show_binary_exit 'mount'
-show_binary_exit 'dmesg'
 show_binary_exit 'df -h'
+show_file '/etc/fstab'
+show_file '/etc/mtab'
+
+# devices related info
 show_binary_exit 'ls -lR /dev'
 show_binary_exit 'lsusb'
 show_binary_exit 'lsusb -v'
+
+# network related info
 show_binary_exit '/sbin/ifconfig'
 show_binary_exit '/sbin/route -n'
 show_file '/etc/network/interfaces'
 
-show_file '/etc/fstab'
-show_file '/etc/mtab'
+# modules related info
 show_file '/etc/modules'
 show_binary_exit '/sbin/lsmod'
 
+# grub related info
 show_file '/boot/grub/menu.lst'
 
-# Ficheros del /proc
+# 'proc' related info
 for i in /proc/{apm,cmdline,cpuinfo,crypto,devices,dma,execdomains,fb,filesystems,interrupts,iomem,ioports,loadavg,locks,meminfo,misc,modules,mounts,mtrr,partitions,bus/pci/devices,slabinfo,stat,swaps,uptime,version} ; do
    show_file $i
 done
 
-# Información del lspci en formato para informe de discover
+# suitable lspci info for 'discover'
 show_binary_exit "(lspci -n ; lspci) | sort"
 
-zenity --question --title "$NOMBRE_PROGRAMA" --text \
-"El informe se ha generado correctamente.
+zenity --question --title "$APP_NAME" --text \
+$"Report has been successfuly generated.
 
-¿Desea revisar el informe?"
+Do you wish to review the report?"
 
 if [ $? == 0 ]; then
-  zenity  --text-info --title "$NOMBRE_PROGRAMA" --width=700 --height=500 --filename $FICHERO_SALIDA
+  zenity  --text-info --title "$APP_NAME" --width=700 --height=500 --filename $OUTPUT_FILE
 fi
 
-if [ ! -f "$DIRECTORIO_FINAL/$FICHERO_FINAL.bz2" ]; then
-  mv $FICHERO_SALIDA $DIRECTORIO_FINAL/$FICHERO_FINAL
-  bzip2 $DIRECTORIO_FINAL/$FICHERO_FINAL
-  chown $REAL_USER:users "$DIRECTORIO_FINAL/$FICHERO_FINAL.bz2"
-  rm -f $DIRECTORIO_FINAL/$FICHERO_FINAL
-  zenity --info --title "$NOMBRE_PROGRAMA" --text "El informe se ha guardado comprimido en su escritorio con el nombre $FICHERO_FINAL.bz2" 
+if [ ! -f "$DESTDIR/$FINAL_LOGFILE.bz2" ]; then
+  mv $OUTPUT_FILE $DESTDIR/$FINAL_LOGFILE
+  bzip2 $DESTDIR/$FINAL_LOGFILE
+  chown $REAL_USER:users "$DESTDIR/$FINAL_LOGFILE.bz2"
+  rm -f $DESTDIR/$FINAL_LOGFILE
+  zenity --info --title "$APP_NAME" --text $"Report has been stored compressed in $DESTDIR/$FINAL_LOGFILE.bz2"
 else
-  zenity --warning --title "$NOMBRE_PROGRAMA" --text \
-"Ya existe un informe en $DIRECTORIO_FINAL/$FICHERO_FINAL.bz2 de una ejecución anterior.
+  zenity --warning --title "$APP_NAME" --text \
+$"It does already exist a report file in $DESTDIR/$FINAL_LOGFILE.bz2, maybe, from a previous run of this utility
 
-¿Desea sobreescribir su contenido con la nueva información?" 
+Do you want to overwrite it with the new report?"
 
   if [ $? == 0 ]; then
-    rm -f $DIRECTORIO_FINAL/$FICHERO_FINAL.bz2
-    mv $FICHERO_SALIDA $DIRECTORIO_FINAL/$FICHERO_FINAL
-    bzip2 $DIRECTORIO_FINAL/$FICHERO_FINAL
-    chown $REAL_USER:users "$DIRECTORIO_FINAL/$FICHERO_FINAL.bz2"
-    rm -f $DIRECTORIO_FINAL/$FICHERO_FINAL
-    zenity --info --title "$NOMBRE_PROGRAMA" --text "El informe se ha guardado comprimido en su escritorio con el nombre $FICHERO_FINAL.bz2"
+    rm -f $DESTDIR/$FINAL_LOGFILE.bz2
+    mv $OUTPUT_FILE $DESTDIR/$FINAL_LOGFILE
+    bzip2 $DESTDIR/$FINAL_LOGFILE
+    chown $REAL_USER:users "$DESTDIR/$FINAL_LOGFILE.bz2"
+    rm -f $DESTDIR/$FINAL_LOGFILE
+    zenity --info --title "$APP_NAME" --text $"Report has been stored compressed in $DESTDIR/$FINAL_LOGFILE.bz2"
   fi
 fi
